# ç½‘ç«™é…ç½®
Config:
  # ä¾§æ çŠ¶æ€
  hide: true
  # ç½‘é¡µæ ‡é¢˜
  title: Tabox
  # ç½‘ç«™å›¾æ ‡
  logo: avatar.jpg
  # å›¾æ ‡è·³è½¬
  link: https://luoyuanxiang.top/tabox

# æœç´¢åˆ—è¡¨
Search:
  # æœç´¢ç»„
  æœç´¢:
    Bing: https://www.bing.com/search?q=
    Google: https://www.google.com/search?q=
    Baidu: https://www.baidu.com/s?wd=
    Translate: https://fanyi.baidu.com/mtpe-individual/multimodal?query=


  ä»£ç :
    Github: https://github.com/search?q=
    NPM: https://www.npmjs.com/search?q=
    Docker: https://hub.docker.com/search?q=

  ç¤¾åŒº:
    Bilibili: https://search.bilibili.com/all?keyword=
    Juejin: https://juejin.im/search?query=
    Zhihu: https://www.zhihu.com/search?q=
    StackOverflow: https://stackoverflow.com/search?q=
    Kaifa: https://kaifa.baidu.com/searchPage?wd=
    Fofa: https://fofa.info/result?qbase64=

# æ ‡ç­¾åˆ—è¡¨
Tabox:
  # æ ‡ç­¾ç»„
  Common:
    logo: https://cdn.worldvectorlogo.com/logos/onenote-2.svg
    description: å¸¸ç”¨ç½‘ç«™

    Java:
      - https://pdai.tech/
      - Java å…¨æ ˆçŸ¥è¯†ä½“ç³»
    Helloç®—æ³•:
      - https://www.hello-algo.com/
      - Hello ç®—æ³•
      - https://www.hello-algo.com/assets/images/favicon.png
    Tools:
      - https://tool.lu/
      - åœ¨çº¿å·¥å…·
    WdByte:
      - https://www.wdbyte.com/
      - æœªè¯»ä»£ç 
      - https://www.wdbyte.com/static/fav.png
    Bugstack:
      - https://bugstack.cn/
      - å°å‚…å“¥ bugstack è™«æ´æ ˆ
    BiliBili:
      - https://www.bilibili.com/
      - å¹´è½»äººçš„å¹³å°
      # - https://www.bilibili.com/favicon.ico
    Github:
      - https://github.com/
      - å…¨çƒå¼€æºç¤¾åŒº
      # - https://github.com/favicon.ico
    Zhihu:
      - https://www.zhihu.com/
      - çŸ¥ä¹é—®ç­”ç¤¾åŒº
    Juejin:
      - https://juejin.cn/
      - æ˜é‡‘æŠ€æœ¯ç¤¾åŒº
      - https://lf-web-assets.juejin.cn/obj/juejin-web/xitu_juejin_web/static/favicons/apple-touch-icon.png
    Amap:
      - https://ditu.amap.com/
      - é«˜å¾·åœ°å›¾
    TongJi:
      - https://tongji.baidu.com/
      - ç™¾åº¦ç»Ÿè®¡
    Weibo:
      - https://weibo.com/
      - å¾®åšç¤¾äº¤å¹³å°
    CSDN:
      - https://blog.csdn.net/
      - CSDNåšå®¢

  # æ ‡ç­¾ç»„
#  Website:
#    logo: https://cdn.worldvectorlogo.com/logos/powerpoint-2.svg
#    description: æˆ‘çš„ç½‘ç«™
#
#    Blog:
#      - https://luoyuanxiang.top
#      - æˆ‘çš„åšå®¢
#    Tabox:
#      - https://luoyuanxiang.top/tabox
#      - æ ‡ç­¾é¡µ
#    Qexo:
#      - https://qexo.luoyuanxiang.top
#      - åå°ç®¡ç†
#      - https://unpkg.com/qexo-static@2.4.0/qexo/images/icon.png

  Tools:
    logo: https://cdn.worldvectorlogo.com/logos/outlook-1.svg
    description: å®ç”¨ç½‘ç«™


    Tencent:
      - https://console.cloud.tencent.com/
      - è…¾è®¯äº‘
    CDN:
      - https://dash.cloudflare.com/
      - ç½‘ç«™åŠ é€Ÿ
    MSDN:
      - https://msdn.itellyou.cn
      - ç³»ç»Ÿé•œåƒ
    Gitee:
      - https://gitee.com
      - å›½å†…å¼€æºç¤¾åŒº
    Coding:
      - https://coding.net
      - ä»£ç æ‰˜ç®¡
      - https://help-assets.codehub.cn/enterprise/guanwang/favicon.ico
    NPM:
      - https://www.npmjs.com
      - Node ä»“åº“
      - https://static.npmjs.com/b0f1a8318363185cc2ea6a40ac23eeb2.png
    Docker:
      - https://hub.docker.com
      - Docker ä»“åº“
      - https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/docker.svg
    ProcessOn:
      - https://www.processon.com/
      - å…è´¹åœ¨çº¿æµç¨‹å›¾æ€ç»´å¯¼å›¾
    HDmoli:
      - https://www.hdmoli.pro/
      - HDmoliåœ¨çº¿è§†é¢‘
    Vercel:
      - https://vercel.com/
      - Vercel
    Surfboard:
      - https://getsurfboard.org/surfboard-download/
      - Surfboard ä¸‹è½½
    é˜¿é‡Œäº‘é‚®ç®±:
      - https://alimail.console.aliyun.com/
      - é˜¿é‡Œäº‘é‚®ç®±
      - https://img.alicdn.com/tfs/TB1_ZXuNcfpK1RjSZFOXXa6nFXa-32-32.ico
    Diagrams:
      - https://app.diagrams.net/
      - æ€ç»´å¯¼å›¾
    ZZZMH:
      - https://bz.zzzmh.cn/index
      - æç®€å£çº¸
    ZiXiaoYun:
      - https://zixiaoyun.com/
      - è–„è·å›¾åºŠ - å›¾ç‰‡ã€æ–‡æ¡£ã€éŸ³è§†é¢‘è½¬é“¾æ¥
    ktLogo:
      - https://tools.kalvinbg.cn/convenience/icon
      - ktLogo
    WallHaven:
      - https://wallhaven.cc/
      - å£çº¸
    Natapp:
      - https://natapp.cn/
      - å¼€å¯æ‚¨çš„å†…ç½‘ç©¿é€ä¹‹æ—…
    Tinypng:
      - https://tinypng.com/
      - å‹ç¼©å›¾ç‰‡
      - https://tinypng.com/images/favicon.ico
    MyHkw:
      - https://myhkw.cn/
      - éŸ³ä¹æ’­æ”¾å¹³å°
    JDK:
      - https://adoptium.net/zh-CN/temurin/releases/
      - JDK ä¸‹è½½å¹³å°
      - https://adoptium.net/favicon-32x32.png
    Hitokoto:
      - https://developer.hitokoto.cn/
      - éšæœºä¸€è¨€
    DynamicTP:
      - https://dynamictp.cn/
      - ğŸ”¥ğŸ”¥ğŸ”¥ åŸºäºé…ç½®ä¸­å¿ƒçš„è½»é‡çº§åŠ¨æ€å¯ç›‘æ§çº¿ç¨‹æ± 
    BaiduAi:
      - https://inspiration.baidu.com/app?source=aisearch&isNewPage=0
      - çµæ„Ÿä¸­å¿ƒ
    Canva:
      - https://www.canva.cn/
      - ç”»å›¾
    Shields:
      - https://shields.io/
      - åŠ¨æ€å¾½ç« 
    Redis:
      - https://console.upstash.com/redis
      - å…è´¹Redis
      - https://console.upstash.com/static/icons/apple-touch-icon.png
    Moeyy:
      - https://github.moeyy.xyz/
      - GitHub åŠ é€Ÿä¸‹è½½æ–‡ä»¶
    Yizhihongxing:
      - https://order.yizhihongxing.org/
      - ä¸€æçº¢æ å‡ºå¢™æ¥
    Gnomic:
      - https://www.gnomic.cn/agentCenter/index?aixuanfeng
      - æ™ºèƒ½ä½“
      - https://buff8.oss-cn-shanghai.aliyuncs.com/sublime_words/logo_1.png
    Uestcedu:
      - https://sso-idp.uestcedu.com/login
      - ç”µå­ç§‘æŠ€å¤§å­¦ç™»å½•
      - https://sso.uestcedu.com/cdn.yufuid.com/images/appearance/tn-c7cc65570ae049878a7e9d3ea4215121-1668416206619.png
    BigAirport:
      - https://bigairport-mirror.com/
      - å¤§æœºåœº Official Mirror Site


  Docs:
    logo: https://cdn.worldvectorlogo.com/logos/word-1.svg
    description: å¼€å‘å·¥å…·

    Runoob:
      - https://www.runoob.com/
      - èœé¸Ÿæ•™ç¨‹
    Vue:
      - https://cn.vuejs.org/
      - Vue æ–‡æ¡£
      - https://cn.vuejs.org/logo.svg
    Yuque:
      - https://www.yuque.com
      - æ–‡æ¡£å¹³å°
    Gitæäº¤è§„èŒƒ:
      - https://zhuanlan.zhihu.com/p/67804026
      - Gitæäº¤è§„èŒƒ
    MySQLæ—¥æœŸé›†åˆ:
      - https://blog.csdn.net/qierkang/article/details/108244337?spm=1001.2014.3001.5501
      - MYSQLæ—¥æœŸé›†åˆæŸ¥è¯¢ä»Šå¤©ã€æ˜¨å¤©ã€æœ¬å‘¨ã€æœ¬æœˆã€ä¸Šæœˆ ã€æœ¬å¹´ã€æœ¬å­£
    äº¬ä¸œè£…æœºå¤§å¸ˆ:
      - https://diy.jd.com/#/recommend
      - äº¬ä¸œè£…æœºå¤§å¸ˆ
      - //storage.360buyimg.com/dlxt/master-of-loader-pc/64eb21e/favicon.ico
    Nginx:
      - https://www.nginx.cn/doc/index.html
      - Nginx ä¸­æ–‡æ–‡æ¡£
    JVM:
      - https://blog.csdn.net/lovewebeye/article/details/80911838
      - JAVA(-Xms,Xmx,Xmn-XX:newSize,-XX:MaxnewSize,-XX:PermSize,-XX:MaxPermSize)åŒºåˆ«
    SpringBoot:
      - https://worktile.com/kb/ask/832138.html
      - springæ€ä¹ˆé‡æ–°åˆå§‹åŒ–bean
      - https://cdn-kb.worktile.com/kb/wp-content/uploads/2022/02/cropped-200-200.jpg
    NodeSeek:
      - https://www.nodeseek.com/
      - NodeSeek
      - https://www.nodeseek.com/static/image/favicon/favicon-32x32.png
    SpringBooté¡¹ç›®ä¸‹å®ç°åŠ¨æ€åŒ–é™æ€æ–‡ä»¶è·¯å¾„æ³¨å†Œ:
      - https://blog.csdn.net/lqzkcx3/article/details/122641111
      - SpringBooté¡¹ç›®ä¸‹å®ç°åŠ¨æ€åŒ–é™æ€æ–‡ä»¶è·¯å¾„æ³¨å†Œ
    MyBatis:
      - https://blog.csdn.net/m0_37317159/article/details/82986085
      - Mybatisä¸­è¿›è¡Œæ‰¹é‡æ›´æ–°ï¼ˆupdateBatchï¼‰
    ElasticSearch:
      - https://blog.csdn.net/csdn_20150804/article/details/105618933
      - ElasticSearchç³»åˆ—ï¼ˆå…­ï¼‰springbootä¸­ä½¿ç”¨QueryBuildersã€NativeSearchQueryå®ç°å¤æ‚æŸ¥è¯¢
    Quarkus:
      - https://quarkus.io/
      - è¶…éŸ³é€ŸäºšåŸå­ Java
    JetBrains:
      - https://r86oxhhvu2.feishu.cn/docs/doccnfISWDcrZshg7ZA9TivqNYc
      - JetBrains å®˜æ–¹æ­£ç‰ˆè´¦å·ï¼Œå…¨å®¶æ¡¶å…¨ç‰ˆæœ¬å…¨å¹³å°éƒ½å¯æ¿€æ´»
      - //lf-scm-cn.feishucdn.com/ccm/pc/web/resource/bear/src/common/assets/favicons/icon_file_doc_nor-256x256.5ecc0ce2486516290b43.png
    Screw:
      - https://gitee.com/leshalv/screw
      - ç®€æ´å¥½ç”¨çš„æ•°æ®åº“è¡¨ç»“æ„æ–‡æ¡£ç”Ÿæˆå·¥å…·
    EasyEs:
      - https://www.easy-es.cn/
      - å¿«é€Ÿå¼€å‘Elasticsearch
    DBTutorial:
      - https://dunwu.github.io/db-tutorial/
      - æ•°æ®åº“æ•™ç¨‹
    Likepoems:
      - https://api.likepoems.com/
      - å¦‚è¯—ï¼ŒAPIæ¥å£æ–‡æ¡£
    Jinrishici:
      - https://www.jinrishici.com/
      - ä»Šæ—¥è¯—è¯
    JAVAåç«¯æ¶æ„å¸ˆ:
      - https://www.processon.com/view/link/61b2313b0e3e74683770741d
      - JAVAåç«¯æ¶æ„å¸ˆ
    SpringCloud:
      - https://springcloud.fun/
      - SpringCloud
    EMQX:
      - https://docs.emqx.com/zh/emqx/latest/deploy/cluster/lb-nginx.html
      - ç”¨ NGINX è´Ÿè½½å‡è¡¡ EMQX é›†ç¾¤
    JTT808:
      - https://jtst.mot.gov.cn/kfs/file/read/8736c9f4c7448cf07f643aa1c3cd6a76
      - JTT808
    PaddleOCR:
      - https://gitee.com/duolabmeng666/paddlehub_ppocr
      - åŸºäº Serverless æ¶æ„éƒ¨ç½²é€šç”¨æ–‡å­—è¯†åˆ« PaddleOCR
    Jenkins:
      - https://www.cnblogs.com/MarlonKang/p/15113394.html
      - window10å¹³å°è¿è¡Œjenkins.warçš„æ’ä»¶å®‰è£…å¤±è´¥çš„è§£å†³
    Pig4cloudVip:
      - https://www.pig4cloud.com/data/doc/pigx/
      - pig4cloud æ–‡æ¡£
    GmsslNginx:
      - https://github.com/wojiushixiaobai/gmssl_nginx
      - å›½å¯† SSL é…ç½®
    Pig4cloud:
      - https://geekdaxue.co/read/pig4cloud@pig/lceu0v
      - pig4cloud æ–‡æ¡£


  Github: # github é…ç½®
    logo: https://cdn.worldvectorlogo.com/logos/excel-4.svg
    description: æˆ‘çš„ä»£ç ä»“åº“
    name: luoyuanxiang # ç”¨æˆ·å
    # ä»“åº“å¿½ç•¥
    Ignore:
      - nest-template
      - tduck-front

  Memo: # å¤‡å¿˜å½•
    logo: https://cdn.worldvectorlogo.com/logos/microsoft-teams-1.svg
    description: å¤‡å¿˜å½•

    content: |
      ä¼¼ä¹æ²¡æœ‰ä»€ä¹ˆä¸œè¥¿éœ€è¦å¤‡å¿˜ï¼
